[project]
name = "supportdesk-rag-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sreenath Tella", email = "tellanad@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
supportdesk-rag-workshop = "supportdesk_rag_workshop:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
